name: wash_wow
description: An all in one solution to you washing problem .

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: 1.2.2
  english_words: ^4.0.0
  provider: ^6.0.0
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  flutter_google_maps_webservices: ^1.1.1
  flutter_secure_storage: ^9.2.2
  profile_photo: ^1.0.3
  flutter_spinbox: ^0.13.1
  image_picker: ^1.1.2
  image_field: ^0.0.10
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.2
  firebase_app_check: ^0.3.1+3
  font_awesome_flutter: ^10.7.0
  material_design_icons_flutter: ^7.0.7296
  blur: ^4.0.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  commitlint_cli: ^0.7.1
  husky: ^0.1.7

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic

  assets:
    - assets/images/logos/Logomarkwhite.png
    - assets/images/logos/Logosmall.png
    - assets/images/avatar/placeholderavatar.png
    - .env.local
