name: wash_wow
description: An all in one solution to you washing problem .

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  http: 1.2.2
  english_words: ^4.0.0
  provider: ^6.0.0
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  flutter_google_maps_webservices: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  commitlint_cli: ^0.7.1
  husky: ^0.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/logos/Logomarkwhite.png
    - assets/images/logos/Logosmall.png
    - .env.local


