name: wash_wow
description: An all in one solution to you washing problem .

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: 1.2.2
  english_words: ^4.0.0
  provider: ^6.0.0
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  flutter_google_maps_webservices: ^1.1.1
  flutter_secure_storage: ^9.2.2
  profile_photo: ^1.0.3
  flutter_spinbox: ^0.13.1
  image_picker: ^1.1.2
  image_field: ^0.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  commitlint_cli: ^0.7.1
  husky: ^0.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/logos/Logomarkwhite.png
    - assets/images/logos/Logosmall.png
    - assets/images/avatar/placeholderavatar.png
    - .env.local
