// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9DvzqzjIMPC_jNRweH9ChQ8SKarvPX8k',
    appId: '1:1069743980031:web:5baecf9886297339e3bbca',
    messagingSenderId: '1069743980031',
    projectId: 'wash-wow-upload-image',
    authDomain: 'wash-wow-upload-image.firebaseapp.com',
    storageBucket: 'wash-wow-upload-image.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtXC7cgXQrdafRn0Lggk07o_KzGtBEAzo',
    appId: '1:1069743980031:android:99afd95e8bab6144e3bbca',
    messagingSenderId: '1069743980031',
    projectId: 'wash-wow-upload-image',
    storageBucket: 'wash-wow-upload-image.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA06JrATe4_huh9vJW13uoQji0RrawKw6s',
    appId: '1:1069743980031:ios:503844120c0a91cbe3bbca',
    messagingSenderId: '1069743980031',
    projectId: 'wash-wow-upload-image',
    storageBucket: 'wash-wow-upload-image.appspot.com',
    iosBundleId: 'com.example.washWow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA06JrATe4_huh9vJW13uoQji0RrawKw6s',
    appId: '1:1069743980031:ios:503844120c0a91cbe3bbca',
    messagingSenderId: '1069743980031',
    projectId: 'wash-wow-upload-image',
    storageBucket: 'wash-wow-upload-image.appspot.com',
    iosBundleId: 'com.example.washWow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9DvzqzjIMPC_jNRweH9ChQ8SKarvPX8k',
    appId: '1:1069743980031:web:4f5c5df94d0e884ae3bbca',
    messagingSenderId: '1069743980031',
    projectId: 'wash-wow-upload-image',
    authDomain: 'wash-wow-upload-image.firebaseapp.com',
    storageBucket: 'wash-wow-upload-image.appspot.com',
  );

}